# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74538fa4a0a284dce71cb5a55f942d8d9958cfcd3b1d0402c8c582d16bcda1d57232d5cc7900729e301d4952db4c9e4a02c38b30c3ab507a88b7edda49828bc

test:
  secret_key_base: cd29223988bddcbf1e0c5ec45a131d697d84d9f4d1cf5d88ec0060743ef8edbcc6d59f35690f64375f5f487656f3a47197b92f1c018b9651a85470cf528f5ef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
